# Generated by Django 3.1.7 on 2021-03-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='final_bid',
            new_name='winner_bid',
        ),
    ]
