# Generated by Django 3.1.7 on 2021-03-15 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210315_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bider',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bider', to=settings.AUTH_USER_MODEL),
        ),
    ]
