# Generated by Django 3.1.7 on 2021-03-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210315_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.ImageField(default=4000, upload_to=''),
        ),
    ]
