# Generated by Django 3.1.7 on 2021-03-18 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_replie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closed_Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('image_url', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.CharField(default='', max_length=64)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('starting_bid', models.IntegerField(default=0)),
                ('current_bid', models.IntegerField(default=0, null=True)),
                ('winner_bid', models.IntegerField(default=0)),
                ('TotalBiders', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Gaming', 'Gaming'), ('Toys', 'Toys'), ('House', 'House'), ('Garden', 'Garden'), ('Groceries', 'Groceries'), ('Vehicles', 'Vehicles'), ('Music', 'Music'), ('Pets', 'Pets'), ('Sports', 'sports')], max_length=20)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_bider', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_current_bider', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
