# Generated by Django 3.1.7 on 2021-03-18 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_closed_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Closed_Listing',
        ),
    ]
