# Generated by Django 3.1.7 on 2021-03-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_delete_closed_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='alert',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='alert',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
