# Generated by Django 3.1.7 on 2021-03-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210317_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
