# Generated by Django 3.1.7 on 2021-03-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closed_at',
            field=models.DateTimeField(default=''),
        ),
    ]
