# Generated by Django 3.1.7 on 2021-03-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210317_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='closed_at',
        ),
        migrations.AddField(
            model_name='listing',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
